# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 09:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('file_url', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('parsed', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('sha1', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=512)),
                ('size', models.IntegerField()),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('tika_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedData',
            fields=[
                ('sha1', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legi.DocumentFile'),
        ),
        migrations.AddField(
            model_name='document',
            name='submit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legi.SubmittedData'),
        ),
    ]
